name: InterfaceAI
options:
  bundleIdPrefix: com.interfaceai
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.2"

packages:
  A2UIRenderer:
    path: ../..

targets:
  InterfaceAI:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        GENERATE_INFOPLIST_FILE: true
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.interfaceai.InterfaceAI
    dependencies:
      - package: A2UIRenderer
